# Generated by Django 3.2 on 2023-09-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devops',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
